SampleCalculator/SampleCalculator/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleCalculator.Controllers
{
    public class CalculatorController : Controller
    {
        // GET: Calculator
        public ActionResult Index()
        {
            if (Request.Form["txt"] != null)
            {
                if (Request.Form["txt"][Request.Form["txt"].Length - 1] == '+' || Request.Form["txt"][Request.Form["txt"].Length - 1] == '-' || Request.Form["txt"][Request.Form["txt"].Length - 1] == '*' || Request.Form["txt"][Request.Form["txt"].Length - 1] == '/')
                {
                    ViewBag.flag = 0;
                    ViewBag.result = Request.Form["txt"];
                }
                else
                {
                    ViewBag.result = GetResult(Request.Form["txt"]);
                    ViewBag.flag = 1;
                }
            }
            return View();
        }

        public string GetResult(string str)
        {
            List<char> symbleList = new List<char>();
            char[] charSymble = { '+', '-', '*', '/' };
            string[] st = str.Split(charSymble);
            for (int i = 0; i < str.Length; i++)
            {
                if (str[i] == '+' || str[i] == '-' || str[i] == '*' || str[i] == '/')
                {
                    symbleList.Add(str[i]);
                }
            }
            double result = Convert.ToDouble(st[0]);
            for (int i = 1; i < st.Length; i++)
            {
                double num = Convert.ToDouble(st[i]);
                int j = i - 1;
                switch (symbleList[j])
                {
                    case '+':
                        result = result + num;
                        break;
                    case '-':
                        result = result - num;
                        break;
                    case '*':
                        result = result * num;
                        break;
                    case '/':
                        result = result / num;
                        break;
                    default:
                        result = 0.0;
                        break;
                }
            }
            return result.ToString();
        }

        // GET: Calculator/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Calculator/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calculator/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Calculator/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Calculator/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Calculator/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Calculator/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SampleCalculator/SampleCalculator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleCalculator.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SampleCalculator/SampleCalculator/Views/Calculator/Index.cshtml
<!--<script src="~/jquery-1.12.4.min.js"></script>-->
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">

    $(function()
    {
        $("#txt").keypress(function(e)
         {
            if (String.fromCharCode(e.keyCode).match(/[^0-9+-/*]/g)) return false;
        });
        $("#txt").height("40px").width("312px");
        $("#b0").click(function() {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("0");
            } else
            {
                $("#txt").val(x + "0")
            }
        });
        $("#b1").click(function()
        {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("1");
            } else
            {
                $("#txt").val(x + "1")
            }
        });
        $("#b2").click(function()
        {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("2");
            } else
            {
                $("#txt").val(x + "2")
            }
        });
        $("#b3").click(function()
          {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("3");
            } else
            {
                $("#txt").val(x + "3")
            }
        });
        $("#b4").click(function()
         {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("4");
            } else
            {
                $("#txt").val(x + "4")
            }
        });
        $("#b5").click(function()
         {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("5");
            } else
            {
                $("#txt").val(x + "5")
            }
        });
        $("#b6").click(function()
         {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("6");
            } else
            {
                $("#txt").val(x + "6")
            }
        });
        $("#b7").click(function()
          {
            var x = document.getElementById("txt").value;
            if (x == "0")

           {
                $("#txt").val("7");
            } else
            {
                $("#txt").val(x + "7")
            }
        });
        $("#b8").click(function()
          {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("8");
            } else
            {
                $("#txt").val(x + "8")
            }
        });
        $("#b9").click(function()
         {
            var x = document.getElementById("txt").value;
            if (x == "0")
            {
                $("#txt").val("9");
            } else
            {
                $("#txt").val(x + "9")
            }
        });
        $("#div").click(function()
          {
            var x = document.getElementById("txt").value;
            var y = x.slice(-1)
            if (y == "/" || y == "+" || y == "*" || y == "-") {} else {
                $("#txt").val(x + "/")
            }
        });
        $("#multy").click(function()
          {
            var x = document.getElementById("txt").value;
            var x = document.getElementById("txt").value;
            var y = x.slice(-1)
            if (y == "/" || y == "+" || y == "*" || y == "-") {} else {
                $("#txt").val(x + "*")
            }
        });
        $("#sub").click(function()
          {
            var x = document.getElementById("txt").value;
            var x = document.getElementById("txt").value;
            var x = document.getElementById("txt").value;
            var y = x.slice(-1)
            if (y == "/" || y == "+" || y == "*" || y == "-") {} else {
                $("#txt").val(x + "-")
            }
        });
        $("#add").click(function()
         {
            var x = document.getElementById("txt").value;
            var x = document.getElementById("txt").value;
            var x = document.getElementById("txt").value;
            var x = document.getElementById("txt").value;
            var y = x.slice(-1)
            if (y == "/" || y == "+" || y == "*" || y == "-") {} else {
                $("#txt").val(x + "+")
            }
        });
        $("#dot").click(function()
          {
            var x = document.getElementById("txt").value;
            var y = x.slice(-1)
            if (y == ".") {} else
            {
                $("#txt").val(x + ".")
            }
        });
        $("#ce").click(function()
        {
            var x = document.getElementById("txt").value;
            $("#txt").val(x.substring(0, x.length - 1))
        });
    });
</script>
<style>
    body {
        background-image: url("Image/images.jpg");
    }

    #d1 {
        border: 1px solid black;
        height: 340px;
        width: 340px;
    }
</style>
<br /><br /><br /><br /><br /><br /><br />
<center>
    <div id="d1">
        @using (@Html.BeginForm("Index", "Calculator"))
        {
            <table style="height:25%;border:thick">
                <tr>
                    <td colspan="4">
                        <center>
                            <h2>My Calculator</h2>
                        </center>
                    </td>
                </tr>
                <tr>
                    <td colspan="4">@Html.TextBox("txt", (string)ViewBag.result)</td>
                </tr>
                <tr>
                    <td><input type="button" id="b7" value="7" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="b8" value="8" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="b9" value="9" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="div" value="/" style="height:40px;width:75px" /></td>
                </tr>
                <tr>
                    <td><input type="button" id="b4" value="4" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="b5" value="5" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="b6" value="6" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="multy" value="*" style="height:40px;width:75px" /></td>
                </tr>
                <tr>
                    <td><input type="button" id="b1" value="1" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="b2" value="2" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="b3" value="3" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="sub" value="-" style="height:40px;width:75px" /></td>
                </tr>
                <tr>
                    <td><input type="button" id="b0" value="0" style="height:40px;width:75px" /></td>
                    <td><input type="button" id="dot" value="." style="height:40px;width:75px" /></td>
                    <td><input type="button" id="add" value="+" style="height:40px;width:75px" /></td>
                    <td><input type="submit" id="eq" value="=" style="height:40px;width:75px" /></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="button" id="ce" value="CE" style="height:40px;width:155px" />
                    </td>
                    <td colspan="2">
                        <input type="reset" id="re" value="Clear" style="height:40px;width:155px" />
                    </td>
                </tr>
                <tr>
                    <td colspan="4">
                        <center>
                            <h2>Result : @ViewBag.result</h2>
                        </center>
                    </td>
                </tr>
            </table>
        }
    </div>
</center>
@if (@ViewBag.flag == 0)
{
    Response.Write("<script> alert('Right value is missing.')     </script>");
}   

SampleCalculator/SampleCalculator/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SampleCalculator/SampleCalculator/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SampleCalculator/SampleCalculator/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SampleCalculator/SampleCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>